# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Explore_Reactive_Programming' do

  use_frameworks!

  	pod 'RxSwift',    '~> 4.0'
   	pod 'RxCocoa',    '~> 4.0'
end
